-- CreateEnum
CREATE TYPE "HistoryAction" AS ENUM ('CREATED', 'UPDATED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'ACTIVATED', 'EXPIRED', 'SOLD', 'BOOSTED', 'RESTORED', 'DELETED', 'PERMANENT_DELETE');

-- CreateEnum
CREATE TYPE "ReportReason" AS ENUM ('SOLD', 'DUPLICATE', 'FAKE_INFORMATION', 'FRAUD', 'WRONG_PRICE', 'WRONG_CATEGORY', 'COPYRIGHT', 'SPAM', 'INAPPROPRIATE', 'OTHER');

-- CreateEnum
CREATE TYPE "ReportStatus" AS ENUM ('PENDING', 'REVIEWING', 'RESOLVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "BoostType" AS ENUM ('FEATURED', 'TOP', 'VIP', 'PREMIUM');
